services:
  web:
    build:
      context: .
      target: backend
    
    working_dir: /backend/gym
    env_file:
      - ./backend/.env
    command: >
      bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py createsuperuser --noinput || true &&
        gunicorn gym.wsgi:application --bind 0.0.0.0:8000 --log-level debug
      "
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym

volumes:
  postgres_data:
