openapi: 3.0.3
info:
  title: Gym-Project
  version: 0.0.1
  description: Inżynieria Oprogramowania 2025
paths:
  /api/account/:
    get:
      operationId: api_account_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/account/activities:
    get:
      operationId: api_account_activities_list
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: ''
  /api/account/login:
    post:
      operationId: api_account_login_create
      tags:
      - api
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/account/orders:
    get:
      operationId: api_account_orders_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/account/register:
    post:
      operationId: api_account_register_create
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/events/:
    get:
      operationId: api_events_list
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDate'
          description: ''
  /api/events/join/{id}:
    post:
      operationId: api_events_join_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/events/quit/{id}:
    post:
      operationId: api_events_quit_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /api/offers/:
    get:
      operationId: api_offers_list
      tags:
      - api
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
          description: ''
  /api/offers/select/:
    post:
      operationId: api_offers_select_create
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    Event:
      type: object
      description: |-
        Serializer for Events, related objects are nested.
        This serializer should be used only for viewing
      properties:
        id:
          type: integer
          readOnly: true
        number_of_participants:
          type: integer
        person_limit:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        event_type:
          allOf:
          - $ref: '#/components/schemas/Nested'
          readOnly: true
        coach:
          allOf:
          - $ref: '#/components/schemas/Nested'
          readOnly: true
      required:
      - coach
      - event_type
      - id
      - number_of_participants
      - person_limit
    EventDate:
      type: object
      description: This serializer should be used only for viewing
      properties:
        event:
          $ref: '#/components/schemas/Event'
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        room:
          allOf:
          - $ref: '#/components/schemas/Nested'
          readOnly: true
      required:
      - end_time
      - event
      - room
      - start_time
    Nested:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Event type name
          maxLength: 128
        description:
          type: string
          title: Event description
      required:
      - description
      - id
      - name
    Offer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        duration_days:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
      required:
      - description
      - duration_days
      - id
      - name
      - price
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - email
      - first_name
      - id
      - last_name
      - password
      - username
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
