openapi: 3.0.3
info:
  title: Gym-Project
  version: 0.0.1
  description: Inżynieria Oprogramowania 2025
paths:
  /events:
    get:
      operationId: events_list
      tags:
      - events
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: ''
components:
  schemas:
    Event:
      type: object
      description: |-
        Serializer for Events, related objects are nested.
        This serializer should be used only for viewing
      properties:
        id:
          type: integer
          readOnly: true
        dates:
          type: array
          items:
            $ref: '#/components/schemas/EventDate'
        person_limit:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        event_type:
          allOf:
          - $ref: '#/components/schemas/Nested'
          readOnly: true
        coach:
          allOf:
          - $ref: '#/components/schemas/Nested'
          readOnly: true
      required:
      - coach
      - dates
      - event_type
      - id
      - person_limit
    EventDate:
      type: object
      description: This serializer should be used only for viewing
      properties:
        weekday:
          type: string
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        room:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          title: Room number
          nullable: true
      required:
      - end_time
      - start_time
      - weekday
    Nested:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Event type name
          maxLength: 128
        description:
          type: string
          title: Event description
      required:
      - description
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
