# Generated by Django 5.1.7 on 2025-04-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_coach_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='events.event', verbose_name='Event'),
        ),
    ]
