# Generated by Django 5.1.7 on 2025-04-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdate_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.room'),
        ),
    ]
